
var __Tel__ = "400-968-9088";
var html = [];
html.push('<section id="conatcat-info">');
html.push('<div class="container">');
html.push('<div class="row">');
html.push('<div class="col-sm-8">');
html.push('<div class="media contact-info wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">');
html.push('<div class="pull-left">');
html.push('<i class="fa fa-phone"></i>');
html.push('</div>');
html.push('<div class="media-body">');
html.push('<h2 style="font-weight:400">我们为用户提供24小时的在线服务</h2>');
html.push('<p>您可以拨打我们的全国400客服电话' + __Tel__ + '（工作日9:00-18:00），或者通过在线客服联系我们，同时还欢迎您关注我们的微信公众服务号fenghuangzj。');
html.push('</p>');
html.push('</div>');
html.push('</div>');
html.push('</div>');
html.push('<div style="margin:20px 0 0 1000px;font-size:20px;">');
html.push('<div style="height:45px;width:160px;background:#b9090e;-moz-border-radius:7px;-webkit-border-radius:7px;border-radius:7px;">');
html.push('<a href="#">');
html.push('<div style="text-align:center;line-height:45px;font-size:20px;color:#fff;">' + __Tel__ + '</div>');
html.push('</a>');
html.push('</div>');
html.push('</div>');
html.push('</div>');
html.push('</div><!--/.container-->');
html.push('</section><!--/#conatcat-info-->');
document.write(html.join(''));